# Generated by Django 3.1.7 on 2021-03-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='snippettable',
            new_name='snippet_table',
        ),
    ]
