# Generated by Django 3.1.7 on 2021-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210324_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet_table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
