# Generated by Django 3.1.7 on 2021-03-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
