# Generated by Django 3.1.7 on 2021-04-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeforce_submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=122)),
                ('language', models.CharField(max_length=122)),
                ('time', models.CharField(max_length=122)),
                ('memory', models.CharField(max_length=122)),
                ('solution', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
