# Generated by Django 3.1.7 on 2021-04-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_codeforce_submissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='codeforce_submissions',
            new_name='codeforce_submission',
        ),
    ]
